import request from './request'

export const accountLogin = (user,pass) => request.post({ url:'http://localhost:3000/login', withCredentials:true,data:{name:user,pass:pass}})
export const commentDelete = (commentId) => request.post({ url:'http://localhost:3000/comment/commentDelete',data:{commentId}})
export const getThumbsUp = (user) => request.post({ url:'http://localhost:3000/comment/getThumbsUp',data:{user}})
export const getThumbs = (commentId) => request.post({ url:'http://localhost:3000/comment/getThumbs',data:{commentId}})
export const thumbsUp = (user,commentId) => request.post({ url:'http://localhost:3000/comment/thumbsUp',data:{user,commentId}})
export const thumbsDown= (user,commentId) => request.post({url:'http://localhost:3000/comment/thumbsDown',data:{user,commentId}})
export const submit = (drafid,article,title,user,time,type) => request.post({url:'http://localhost:3000/edit/insertArticle',data:{drafid,article,title,user,time,type}})
export const createDraf = (drafid,article,title,user,time,type) => request.post({url:'http://localhost:3000/edit/insertDraf',data:{drafid,article,title,user,time,type}})
export const showDraf = (drafid) => request.get({url:`http://localhost:3000/edit/showDraf?drafid=${drafid}`})
export const logout = () => request.post({url:'http://localhost:3000/login/logout',withCredentials:true})
export const regin = (user,pass) => request.post({url:'http://localhost:3000/regin',data:{name:user,pass}})
export const articleList = (name) => request.get({url:`http://localhost:3000/person/articleList?name=${name}`})
export const drafList = (name) => request.get({url:`http://localhost:3000/person/drafList?name=${name}`})
export const indexData = (start,end) => request.get({url:`http://localhost:3000/index?start=${start}&end=${end}`})
export const articleShow = (drafid) => request.get({url:`http://localhost:3000/articleShow/${drafid}`})
export const agree = (drafid,name) => request.post({url:`http://localhost:3000/articleShow/agree`,data:{drafid,user:name}})
export const agreeToggle = (drafid,name) => request.post({url:`http://localhost:3000/articleShow/agreeToggle`,data:{drafid,user:name}})
export const disagree = (drafid,name) => request.post({url:`http://localhost:3000/articleShow/disagree`,data:{drafid,user:name}})
export const disagreeToggle = (drafid,name) => request.post({url:`http://localhost:3000/articleShow/disagreeToggle`,data:{drafid,user:name}})
export const comment = (name,articleId,commentId,content) => request.post({url:'http://localhost:3000/comment',data:{user:name,articleId,commentId,content}})
export const getComment = (articleId) => request.post({url:'http://localhost:3000/comment/getData',data:{articleId}})
export const getComment_second = (commentId) => request.post({url:'http://localhost:3000/comment/getData_2',data:{commentId}})
export const response = (name,articleId,commentId,belongComment,belongId,belongUser,content) => request.post({url:'http://localhost:3000/comment/response',data:{user:name,articleId,commentId,belongComment,belongId,belongUser,content}})
